//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tictactoe {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("tictactoe.Resources.en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string LanguageOption {
            get {
                return ResourceManager.GetString("LanguageOption", resourceCulture);
            }
        }
        
        internal static string GameOptions {
            get {
                return ResourceManager.GetString("GameOptions", resourceCulture);
            }
        }
        
        internal static string GameOption1 {
            get {
                return ResourceManager.GetString("GameOption1", resourceCulture);
            }
        }
        
        internal static string GameOption2 {
            get {
                return ResourceManager.GetString("GameOption2", resourceCulture);
            }
        }
        
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        internal static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        internal static string SelectMarker {
            get {
                return ResourceManager.GetString("SelectMarker", resourceCulture);
            }
        }
        
        internal static string InvalidPosition {
            get {
                return ResourceManager.GetString("InvalidPosition", resourceCulture);
            }
        }
        
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        internal static string IsWinner {
            get {
                return ResourceManager.GetString("IsWinner", resourceCulture);
            }
        }
        
        internal static string GameDraw {
            get {
                return ResourceManager.GetString("GameDraw", resourceCulture);
            }
        }
        
        internal static string EnterPosition {
            get {
                return ResourceManager.GetString("EnterPosition", resourceCulture);
            }
        }
    }
}
